### ISSUE TITLE
Prepare Baram publication

### ISSUE THREAD

**Issue by lks21c** [lks21c/baram#62]
## Abstract

To release Baram on public, we should refactor code and tc in Baram and migrate some methods into Baram.

## Items
- Migrate engine methods into Baram.
- pass all TC.
  - Not to use specific data, replace temp file and data in TC.
- Coverage up to 90% on every TC class.
- Refactor some methods
  - ex) enhance s3 list object pagination up to 1000 items.

**Comment by lks21c** [comment]
## TODO

I pushed https://github.com/lks21c/baram/tree/feature/0.4.5 and we can co-work on the branch.

Make all TC passed and increase coverge up to 90%.

- [ ] test_athena_manager, @Baescott 
- [ ] test_s3_manager, @alprinf 
- [ ] test_glue_manager, @Baescott 
- [ ] test_sagemaker_manager, @alprinf 
- [ ] add additional methods into Baram, @lks21c 
- [ ] refactor existing s3 methos, @lks21c 

You must uncomment existing TC and correct it.
Optionally, you can add necessary methods into the manager and attach tc as well.

Hopefully, Due should be until `4/26`.

```
Name                         Stmts   Miss  Cover   Missing
----------------------------------------------------------
baram/airflow_manager.py         8      2    75%   15, 24
baram/async_crawler.py          17      2    88%   21-22
baram/athena_manager.py         43     43     0%   1-151
baram/conf_manager.py           13      0   100%
baram/ec2_manager.py           164     56    66%   22-24, 36-46, 54-70, 90-92, 104-106, 164, 167-168, 177-182, 192, 205-207, 216-219, 332, 343, 354, 363-364, 375, 400, 412
baram/ecr_manager.py            10      2    80%   19, 32
baram/efs_manager.py            36     16    56%   53-56, 65-80
baram/glue_manager.py          114     36    68%   60, 71, 148, 162, 166-171, 183, 201-204, 228, 257, 269-272, 284-287, 307-322, 339
baram/iam_manager.py            34      4    88%   65, 75, 85, 111
baram/kms_manager.py            13      4    69%   33-36
baram/lambda_manager.py         26     12    54%   31, 43-60
baram/log_manager.py            13      0   100%
baram/poetry_manager.py         13      0   100%
baram/process_manager.py        12      1    92%   23
baram/requests_manager.py       12      0   100%
baram/s3_manager.py            147     27    82%   121-123, 141-143, 172, 177-179, 219, 221, 230, 252-257, 267, 316-318, 328-329, 332-339
baram/sagemaker_manager.py     122     77    37%   47-55, 62-67, 76-92, 97-140, 145-169, 176-178, 191-193, 266, 272-276, 279-283
```
